const data = [
  {
    img: "https://upload.wikimedia.org/wikipedia/tr/b/b6/Manchester_United_FC_logo.png",
    title: "Manchester United FC",
    stadyum: "Old Trafford",
    capacity: "74.310",
  },
  {
    img: "https://upload.wikimedia.org/wikipedia/tr/9/92/Arsenal_Football_Club.png",
    title: "Arsenal FC",
    stadyum: "Emirates Stadyumu",
    capacity: "60.361",
  },
  {
    img: "https://upload.wikimedia.org/wikipedia/tr/f/f6/Manchester_City.png",
    title: "Manchester City FC",
    stadyum: "Etihad Stadium",
    capacity: "55.097",
  },
  {
    img: "https://upload.wikimedia.org/wikipedia/tr/3/3f/150px-Liverpool_FC_logo.png",
    title: "Liverpool FC",
    stadyum: "Anfield",
    capacity: "53.394",
  },
  {
    img: "https://upload.wikimedia.org/wikipedia/tr/thumb/2/27/Chelsea_FC_arma.svg/200px-Chelsea_FC_arma.svg.png",
    title: "Chelsea FC",
    stadyum: "Stamford Bridge",
    capacity: "40.834",
  },
  {
    img: "https://upload.wikimedia.org/wikipedia/tr/7/79/Everton_Logo.png",
    title: "Everton Football Club",
    stadyum: "Goodison Park",
    capacity: "39,572",
  },
  {
    img: "https://upload.wikimedia.org/wikipedia/en/5/56/Newcastle_United_Logo.svg",
    title: "Newcastle United FC",
    stadyum: "St James' Park",
    capacity: "52.387",
  },
  {
    img: "https://upload.wikimedia.org/wikipedia/tr/6/6d/Tottenham_Hotspur.png",
    title: "Tottenham Hotspur FC",
    stadyum: "Tottenham Hotspur Stadyumu",
    capacity: "62.062",
  },
  {
    img: "https://upload.wikimedia.org/wikipedia/tr/thumb/0/0c/Crystal_Palace_FC_logo.svg/800px-Crystal_Palace_FC_logo.svg.png",
    title: "Crystal Palace FC",
    stadyum: "Selhurst Park Stadium",
    capacity: "26.309",
  },
  {
    img: "https://upload.wikimedia.org/wikipedia/tr/6/6c/Wolverhampton_Wanderers.png",
    title: "Wolverhampton Wanderers FC",
    stadyum: "Molineux Stadyumu, Wolverhampton",
    capacity: "32.050",
  },
  {
    img: "https://upload.wikimedia.org/wikipedia/tr/thumb/4/40/Fulham.svg/800px-Fulham.svg.png",
    title: "Fulham FC",
    stadyum: "Craven Cottage",
    capacity: "25,700",
  },
  {
    img: "https://upload.wikimedia.org/wikipedia/tr/e/e3/Brighton%26Hove.png",
    title: "Brighton & Hove Albion FC (Brighton & Hove Albion F.C.)",
    stadyum: "Falmer Stadium",
    capacity: "27.350",
  },
  {
    img: "https://a.espncdn.com/combiner/i?img=/i/teamlogos/soccer/500/393.png",
    title: "Nottingham Forest FC (Nottingham Forest F.C.)",
    stadyum: "The City Ground",
    capacity: "30.576",
  },
  {
    img: "https://upload.wikimedia.org/wikipedia/tr/f/fc/Westham_logo.png",
    title: "West Ham United FC (West Ham United F.C.)",
    stadyum: "Londra Stadyum",
    capacity: "60,000",
  },
  {
    img: "https://upload.wikimedia.org/wikipedia/tr/7/78/Leeds_United_logo.png",
    title: "Leeds United AFC (Leeds United)",
    stadyum: "Elland Road",
    capacity: "37,890",
  },
  {
    img: "https://upload.wikimedia.org/wikipedia/tr/a/a2/Leicester_City_logo.png",
    title: "Leicester City FC",
    stadyum: "King Power Stadyumu",
    capacity: "32.312",
  },
  {
    img: "https://upload.wikimedia.org/wikipedia/en/thumb/f/f9/Aston_Villa_FC_crest_%282016%29.svg/1200px-Aston_Villa_FC_crest_%282016%29.svg.png",
    title: "Aston Villa FC",
    stadyum: "Villa Park",
    capacity: "42.788",
  },
  {
    img: "https://upload.wikimedia.org/wikipedia/en/thumb/2/2a/Brentford_FC_crest.svg/1200px-Brentford_FC_crest.svg.png",
    title: "Brentford FC (Brentford F.C.)",
    stadyum: "Gtech Community Stadium",
    capacity: "12.300",
  },
  {
    img: "https://upload.wikimedia.org/wikipedia/tr/1/16/Southampton_logo_2010.png",
    title: "Southampton FC (Southampton F.C.)",
    stadyum: "St Mary Stadyumu",
    capacity: "32.689",
  },
  {
    img: "https://upload.wikimedia.org/wikipedia/tr/9/98/AFC_Bournemouth.png",
    title: "AFC Bournemouth (A.F.C. Bournemouth)",
    stadyum: "Vitality Stadium",
    capacity: "12.000",
  },
  {
    img: "https://a.espncdn.com/combiner/i?img=/i/teamlogos/soccer/500/381.png",
    title: "Norwich City FC",
    stadyum: "Carrow Road",
    capacity: "27.244",
  },
];
export default data;
